import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createOpenApiDocument, type OpenApiDocument } from "./spec.js";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const openApiPath = resolve(packageRoot, "openapi.json");
export const compatibilityBaselinePath = resolve(packageRoot, "compatibility-baseline.json");
export const generatedClientPath = resolve(packageRoot, "src/generated/client.ts");

export function serializeOpenApi(document: OpenApiDocument = createOpenApiDocument()): string {
  return `${JSON.stringify(document, undefined, 2)}\n`;
}

export function generateClientSource(): string {
  return `// Generated by @vocabulary/api-contract. Do not edit manually.
export interface HealthResponse { readonly status: "ok" }
export interface NotReadyErrorResponse { readonly status: "not_ready" }
export interface ApiError { readonly code: string; readonly message: string; readonly requestId: string }

export interface ApiClientOptions {
  readonly baseUrl: string
  readonly fetch?: typeof globalThis.fetch
}

export function createApiClient(options: ApiClientOptions) {
  const fetchImplementation = options.fetch ?? globalThis.fetch
  const get = async <T>(path: string): Promise<T> => {
    const response = await fetchImplementation(options.baseUrl + path)
    if (!response.ok) throw new Error("API request failed with status " + String(response.status))
    return (await response.json()) as T
  }
  return {
    getLiveness: () => get<HealthResponse>("/v1/health/live"),
    getReadiness: () => get<HealthResponse>("/v1/health/ready"),
  } as const
}
`;
}

export async function generateContract(): Promise<void> {
  await Promise.all([
    writeFile(openApiPath, serializeOpenApi(), "utf8"),
    writeFile(generatedClientPath, generateClientSource(), "utf8"),
  ]);
}

export async function checkGeneratedContract(): Promise<readonly string[]> {
  const expected = [
    [openApiPath, serializeOpenApi()],
    [generatedClientPath, generateClientSource()],
  ] as const;
  const stale: string[] = [];
  for (const [path, content] of expected) {
    if ((await readFile(path, "utf8")) !== content) stale.push(path);
  }
  return stale;
}
